[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

# Tempo Testnet
[rpc_endpoints]
tempo = "https://rpc.testnet.tempo.xyz"

[etherscan]
tempo = { key = "", url = "https://contracts.tempo.xyz" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
