[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/"
]

# Solc compiler settings
solc = "0.8.19"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

# ZKsync specific settings
[profile.zksync]
src = "src"
libs = ["lib"]
fallback_oz = true
is_system = false
mode = "3"

# RPC endpoints
[rpc_endpoints]
lens-testnet = "https://rpc.testnet.lens.xyz"
lens-mainnet = "https://rpc.lens.xyz"

# Etherscan verification
[etherscan]
lens-testnet = { key = "${LENSCAN_API_KEY}", url = "https://block-explorer-verify.testnet.lens.dev/contract_verification" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
